# Generated by Django 3.2.6 on 2021-08-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
